version: '3.8' 
services:  
  nginx: 
    image: nginx:alpine 
    container_name: my-app-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt/live/tomyummaster.duckdns.org:rw
      - ./certs-archive:/etc/letsencrypt/archive:rw
      - ./data/web:/var/www/html:rw
    depends_on:
      - frontend_service
      - backend_service_1
    networks:
      - my-app-network

  frontend_service: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-app-frontend
    networks:
      - my-app-network

  backend_service_1: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-app-backend-1
    env_file:
      - ./backend/.env
    networks:
      - my-app-network

networks: 
  my-app-network: 
    driver: bridge 