version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: my-app-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # เปลี่ยนพาธ Mount และสิทธิ์
      - ./certs:/etc/letsencrypt:ro # <--- **สำคัญ:** Mount โฟลเดอร์ certs บน Host ไปที่ /etc/letsencrypt ใน Container
      # - ./certs-archive:/etc/letsencrypt/archive:ro # ไม่จำเป็นต้อง Mount แยกถ้า ./certs ครอบคลุม /etc/letsencrypt แล้ว
      - ./data/web:/var/www/html:ro # <--- เปลี่ยนเป็น ro
    depends_on:
      - frontend_service
      - backend_service_1
    networks:
      - my-app-network

  frontend_service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-app-frontend
    networks:
      - my-app-network

  backend_service_1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-app-backend-1
    env_file:
      - ./backend/.env
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge